version: "2"

services:
  influxdb:
    image: influxdb:2.0.9
    container_name: influx-local
    # volumes:
    #   - /home/xxx/docker/grafana/influxdb:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: koheiwatanabe0
      DOCKER_INFLUXDB_INIT_PASSWORD: koheiwatanabe1
      DOCKER_INFLUXDB_INIT_ORG: koheihome
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket