apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: influxdb-data  
  namespace: timeseries
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
spec:
  selector:
    matchLabels:
      app: influxdb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:1.7.4
          name: influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-data
            - mountPath: /etc/influxdb/influxdb.conf
              name: influxdb-config
              subPath: influxdb.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secrets
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: influxdb-config
          configMap:
            name: influxdb-config
---
apiVersion: v1  
kind: Service  
metadata:  
  name: influxdb-service  
  namespace: timeseries
spec:  
  selector:  
    app: influxdb  
  ports:  
    - protocol: TCP  
      port: 80  
      targetPort: 8086
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: influx
  namespace: timeseries
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
  - timeseries.kevin-asobi.com
  secretName: secret-influx
  rules:
  - host: timeseries.kevin-asobi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: influx
          servicePort: 80
