apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: influxdb-data  
  namespace: timeseries
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata: